name: Apple
on: # rebuild any PRs and main branch changes
  pull_request:
#    paths:
#      - "KeystoneAuthenticator/**"
  push:
    branches:
      - main
#    paths:
#      - "KeystoneAuthenticator/**"

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
